version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      time: "13:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 10
    versioning-strategy: auto
    rebase-strategy: "auto"
    
    # Tweak: Grouping dependencies to reduce PR noise
    groups:
      dependencies:
        patterns:
          - "*" # Groups everything into one "dependencies" PR
          
    # Tweak: Clean up your git history
    commit-message:
      prefix: "chore"
      include: "scope"

    # Tweak: Ensure someone actually sees them
    assignees:
      - "synle"
      
