version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      time: "13:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 25
    versioning-strategy: auto
    rebase-strategy: auto
    groups:
      # Group 1: UI & Styling (MUI, Emotion, Icons)
      ui-framework:
        patterns:
          - "@mui/*"
          - "@emotion/*"
      
      # Group 2: React Core & Navigation
      react-core:
        patterns:
          - "react"
          - "react-dom"
          - "react-router*"
          - "react-flow-renderer"

      # Group 3: Data Fetching (Tanstack)
      tanstack:
        patterns:
          - "@tanstack/*"

      # Group 4: Azure
      database-drivers:
        patterns:
          - "@azure/*"

      # Group 5: All TypeScript Definitions
      types:
        patterns:
          - "@types/*"
