version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      time: "13:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 15
    versioning-strategy: auto
    rebase-strategy: auto
    groups:
      # UI & Styling (MUI, Emotion, Icons)
      mui
        patterns:
          - "@mui/*"

      emotion
        patterns:
          - "@emotion/*"

      # React Core
      react
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"

      # Data Fetching (Tanstack)
      tanstack-react-query*
        patterns:
          - "@tanstack/react-query*"

      # Database
      azure
        patterns:
          - "@azure/*"

      redis
        patterns:
          - "redis/*"
          - "@types/redis/*"

      # Misc
      babel
        patterns:
          - "@babel/*"
