title: sqlui-native
description: A simple UI client for most SQL Engines written in Electron. It is compatible with Windows, Mac, Ubuntu / Debian and Redhat. It supports most dialects of RMBDs like MySQL, Microsoft SQL Server, Postgres, SQLite and has limited supports for Cassandra, MongoDB and Redis.
show_downloads: true
google_analytics:
app_version: 1.11.12
theme: jekyll-theme-cayman
