title: sqlui-native
description: sqlui-native is a simple UI client for most SQL Engines written in Electron. It is compatible with most desktop OSâ€™s and support most dialects.
show_downloads: true
google_analytics:
app_version: 1.8.1
theme: jekyll-theme-cayman
