title: sqlui-native
description: sqlui-native is a simple UI client for most SQL Engines written in Electron. It is compatible with most desktop OSâ€™s and support most dialects.
show_downloads: true
google_analytics:
app_version: 1.2.0
app_download:
  mac_url: https://github.com/synle/sqlui-native/releases/download/1.2.0/sqlui-native-1.2.0.dmg
  windows_url: https://github.com/synle/sqlui-native/releases/download/1.2.0/sqlui-native.Setup.1.2.0.exe
theme: jekyll-theme-cayman
